# Generated by Django 5.1.4 on 2025-01-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bayer',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
