# Generated by Django 5.1.4 on 2025-01-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_alter_bayer_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bayer',
            name='balance',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='size',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
